# Mostly safe in docker, only network access is allowed
# TODO: use external solution to limit network access for container
sandbox_mode = "danger-full-access"

[projects."/app"]
trust_level = "trusted"
